### ISSUE TITLE
ActionMode dismissed callback

### ISSUE THREAD

**Issue by imsanjaysah** [De-Morgan/flutter-contextual-action-bar#2]
Hi,

First of all thank you for such a nice plugin. It does the job pretty well. 

In one of my use case, I need to hide/unhide a view based on ActionMode enabled/disabled status. I tried to figure it out but could not able to identify if the ActionMode is disabled. Though by using the CounterBuilder I identified that the ActionMode is enabled when itemCount >= 0

Looking forward for your help.

Thanks in advance.

**Comment by De-Morgan** [comment]
Thanks for the feedback, i think what you need is a callback or a stream to
listen to when the actionMode is enabled or disabled. I will try and add
this in the next update. I will let you know when this update is done

**Comment by De-Morgan** [comment]
Hello @Sanjay Sah, i have added this feature, you can check version 1.0.3

**Comment by imsanjaysah** [comment]
@De-Morgan 

Thank you for adding the feature.

I tried to use it. Refer the below code:

```
@override
  void initState() {
    super.initState();
    ActionMode.actionModeEnabledStream<int>(context).listen((bool status) {
      setState(() {
        _actionModeEnabled = status;
      });
    });
  }
```

But it throws an exception:

`════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following ProviderNotFoundException was thrown building DevicesPage(dirty, state: _DevicesPageState#ac953):
Error: Could not find the correct Provider<ItemsController<int>> above this DevicesPage Widget

This likely happens because you used a `BuildContext` that does not include the provider
of your choice. There are a few common scenarios:

- The provider you are trying to read is in a different route.

  Providers are "scoped". So if you insert of provider inside a route, then
  other routes will not be able to access that provider.

- You used a `BuildContext` that is an ancestor of the provider you are trying to read.

  Make sure that DevicesPage is under your MultiProvider/Provider<ItemsController<int>>.
  This usually happen when you are creating a provider and trying to read it immediatly.

  For example, instead of:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // Will throw a ProviderNotFoundError, because `context` is associated
      // to the widget that is the parent of `Provider<Example>`
      child: Text(context.watch<Example>()),
    ),
  }
  ```

  consider using `builder` like so:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // we use `builder` to obtain a new `BuildContext` that has access to the provider
      builder: (context) {
        // No longer throws
        return Text(context.watch<Example>()),
      }
    ),
  }
`

**Comment by De-Morgan** [comment]
This plugin makes use of Provider internally, as a result you can't use the actionModeEnabledStream above the ContextualActionScaffold, please check the Whatsapp example to see how it's being used
